INSERT INTO `health_prob` (`name`, `tier`, `user_id`) VALUES
('Diabetes', '1', '2'),
('Cancer', '3', '1'),
('Alzheimer', '3', '3'),
('Hipertensão', '2', '3'),
('Asma', '2', '1'),
('Alergia', '1', '1'),
('Gripe', '1', '3'),
('Diarreia', '1', '2'),
('Dor de Cabeça', '1', '2'),
('Alergia', '1', '4'),
('Gripe', '1', '4'),
('Diarreia', '1', '4'),
('Dor de Cabeça', '1', '4'),
('Asma', '2', '5'),
('Alergia', '1', '5'),
('Gripe', '1', '5'),
('Alergia', '1', '6'),
('Gripe', '1', '6'),
('Cancer', '3', '6'),
('Alzheimer', '3', '6'),
('Diabetes', '1', '6'),
('Cancer', '3', '6'),
('Alzheimer', '3', '7'),
('Hipertensão', '2', '7'),
('Diarreia', '1', '7'),
('Dor de Cabeça', '1', '7'),
('Diabetes', '1', '8'),
('Cancer', '3', '8'),
('Alzheimer', '3', '8'),
('Gripe', '1', '9'),
('Diarreia', '1', '9');


